spring.profiles.active=local
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
springdoc.swagger-ui.path=/
springdoc.swagger-ui.operationsSorter=alpha
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.data.mongodb.uuid-representation=standard
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.cloud.aws.s3.bucket=${SPRING_CLOUD_AWS_S3_BUCKET}
spring.cloud.aws.sqs.queue=${SPRING_CLOUD_AWS_SQS_QUEUE}
logging.pattern.console=%highlight([%d{yyyy-MM-dd}] [%d{HH:mm:ss}] [%level]) %cyan([%logger]): %msg %n%n
