FROM eclipse-temurin:23-jdk-alpine AS build
RUN apk add --no-cache maven
WORKDIR /source
COPY source/pom.xml .
RUN mvn dependency:go-offline
COPY source .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:23-jre-alpine
WORKDIR /app
COPY --from=build /source/target/*.jar app.jar
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "app.jar"]
