metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - memory
      - network
      - diskio
      - filesystem

processors:
- add_host_metadata: ~
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: "elk-elasticsearch:9200"

setup.kibana:
  host: "elk-kibana:5601"
